/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   lora__protocol__packet__init
                     (Lora__Protocol__Packet         *message)
{
  static const Lora__Protocol__Packet init_value = LORA__PROTOCOL__PACKET__INIT;
  *message = init_value;
}
size_t lora__protocol__packet__get_packed_size
                     (const Lora__Protocol__Packet *message)
{
  assert(message->base.descriptor == &lora__protocol__packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__packet__pack
                     (const Lora__Protocol__Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__packet__pack_to_buffer
                     (const Lora__Protocol__Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__Packet *
       lora__protocol__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__Packet *)
     protobuf_c_message_unpack (&lora__protocol__packet__descriptor,
                                allocator, len, data);
}
void   lora__protocol__packet__free_unpacked
                     (Lora__Protocol__Packet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__lat_lng_pos__init
                     (Lora__Protocol__LatLngPos         *message)
{
  static const Lora__Protocol__LatLngPos init_value = LORA__PROTOCOL__LAT_LNG_POS__INIT;
  *message = init_value;
}
size_t lora__protocol__lat_lng_pos__get_packed_size
                     (const Lora__Protocol__LatLngPos *message)
{
  assert(message->base.descriptor == &lora__protocol__lat_lng_pos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__lat_lng_pos__pack
                     (const Lora__Protocol__LatLngPos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__lat_lng_pos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__lat_lng_pos__pack_to_buffer
                     (const Lora__Protocol__LatLngPos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__lat_lng_pos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__LatLngPos *
       lora__protocol__lat_lng_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__LatLngPos *)
     protobuf_c_message_unpack (&lora__protocol__lat_lng_pos__descriptor,
                                allocator, len, data);
}
void   lora__protocol__lat_lng_pos__free_unpacked
                     (Lora__Protocol__LatLngPos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__lat_lng_pos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__xypos__init
                     (Lora__Protocol__XYPos         *message)
{
  static const Lora__Protocol__XYPos init_value = LORA__PROTOCOL__XYPOS__INIT;
  *message = init_value;
}
size_t lora__protocol__xypos__get_packed_size
                     (const Lora__Protocol__XYPos *message)
{
  assert(message->base.descriptor == &lora__protocol__xypos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__xypos__pack
                     (const Lora__Protocol__XYPos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__xypos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__xypos__pack_to_buffer
                     (const Lora__Protocol__XYPos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__xypos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__XYPos *
       lora__protocol__xypos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__XYPos *)
     protobuf_c_message_unpack (&lora__protocol__xypos__descriptor,
                                allocator, len, data);
}
void   lora__protocol__xypos__free_unpacked
                     (Lora__Protocol__XYPos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__xypos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__generic_pos__init
                     (Lora__Protocol__GenericPos         *message)
{
  static const Lora__Protocol__GenericPos init_value = LORA__PROTOCOL__GENERIC_POS__INIT;
  *message = init_value;
}
size_t lora__protocol__generic_pos__get_packed_size
                     (const Lora__Protocol__GenericPos *message)
{
  assert(message->base.descriptor == &lora__protocol__generic_pos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__generic_pos__pack
                     (const Lora__Protocol__GenericPos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__generic_pos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__generic_pos__pack_to_buffer
                     (const Lora__Protocol__GenericPos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__generic_pos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__GenericPos *
       lora__protocol__generic_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__GenericPos *)
     protobuf_c_message_unpack (&lora__protocol__generic_pos__descriptor,
                                allocator, len, data);
}
void   lora__protocol__generic_pos__free_unpacked
                     (Lora__Protocol__GenericPos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__generic_pos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__no_pos__init
                     (Lora__Protocol__NoPos         *message)
{
  static const Lora__Protocol__NoPos init_value = LORA__PROTOCOL__NO_POS__INIT;
  *message = init_value;
}
size_t lora__protocol__no_pos__get_packed_size
                     (const Lora__Protocol__NoPos *message)
{
  assert(message->base.descriptor == &lora__protocol__no_pos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__no_pos__pack
                     (const Lora__Protocol__NoPos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__no_pos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__no_pos__pack_to_buffer
                     (const Lora__Protocol__NoPos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__no_pos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__NoPos *
       lora__protocol__no_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__NoPos *)
     protobuf_c_message_unpack (&lora__protocol__no_pos__descriptor,
                                allocator, len, data);
}
void   lora__protocol__no_pos__free_unpacked
                     (Lora__Protocol__NoPos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__no_pos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__advertise__data_entry__init
                     (Lora__Protocol__Advertise__DataEntry         *message)
{
  static const Lora__Protocol__Advertise__DataEntry init_value = LORA__PROTOCOL__ADVERTISE__DATA_ENTRY__INIT;
  *message = init_value;
}
void   lora__protocol__advertise__init
                     (Lora__Protocol__Advertise         *message)
{
  static const Lora__Protocol__Advertise init_value = LORA__PROTOCOL__ADVERTISE__INIT;
  *message = init_value;
}
size_t lora__protocol__advertise__get_packed_size
                     (const Lora__Protocol__Advertise *message)
{
  assert(message->base.descriptor == &lora__protocol__advertise__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__advertise__pack
                     (const Lora__Protocol__Advertise *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__advertise__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__advertise__pack_to_buffer
                     (const Lora__Protocol__Advertise *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__advertise__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__Advertise *
       lora__protocol__advertise__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__Advertise *)
     protobuf_c_message_unpack (&lora__protocol__advertise__descriptor,
                                allocator, len, data);
}
void   lora__protocol__advertise__free_unpacked
                     (Lora__Protocol__Advertise *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__advertise__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__bundle_forward__data_entry__init
                     (Lora__Protocol__BundleForward__DataEntry         *message)
{
  static const Lora__Protocol__BundleForward__DataEntry init_value = LORA__PROTOCOL__BUNDLE_FORWARD__DATA_ENTRY__INIT;
  *message = init_value;
}
void   lora__protocol__bundle_forward__init
                     (Lora__Protocol__BundleForward         *message)
{
  static const Lora__Protocol__BundleForward init_value = LORA__PROTOCOL__BUNDLE_FORWARD__INIT;
  *message = init_value;
}
size_t lora__protocol__bundle_forward__get_packed_size
                     (const Lora__Protocol__BundleForward *message)
{
  assert(message->base.descriptor == &lora__protocol__bundle_forward__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__bundle_forward__pack
                     (const Lora__Protocol__BundleForward *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__bundle_forward__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__bundle_forward__pack_to_buffer
                     (const Lora__Protocol__BundleForward *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__bundle_forward__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__BundleForward *
       lora__protocol__bundle_forward__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__BundleForward *)
     protobuf_c_message_unpack (&lora__protocol__bundle_forward__descriptor,
                                allocator, len, data);
}
void   lora__protocol__bundle_forward__free_unpacked
                     (Lora__Protocol__BundleForward *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__bundle_forward__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__ping_pong__init
                     (Lora__Protocol__PingPong         *message)
{
  static const Lora__Protocol__PingPong init_value = LORA__PROTOCOL__PING_PONG__INIT;
  *message = init_value;
}
size_t lora__protocol__ping_pong__get_packed_size
                     (const Lora__Protocol__PingPong *message)
{
  assert(message->base.descriptor == &lora__protocol__ping_pong__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__ping_pong__pack
                     (const Lora__Protocol__PingPong *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__ping_pong__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__ping_pong__pack_to_buffer
                     (const Lora__Protocol__PingPong *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__ping_pong__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__PingPong *
       lora__protocol__ping_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__PingPong *)
     protobuf_c_message_unpack (&lora__protocol__ping_pong__descriptor,
                                allocator, len, data);
}
void   lora__protocol__ping_pong__free_unpacked
                     (Lora__Protocol__PingPong *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__ping_pong__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__set_config__init
                     (Lora__Protocol__SetConfig         *message)
{
  static const Lora__Protocol__SetConfig init_value = LORA__PROTOCOL__SET_CONFIG__INIT;
  *message = init_value;
}
size_t lora__protocol__set_config__get_packed_size
                     (const Lora__Protocol__SetConfig *message)
{
  assert(message->base.descriptor == &lora__protocol__set_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__set_config__pack
                     (const Lora__Protocol__SetConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__set_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__set_config__pack_to_buffer
                     (const Lora__Protocol__SetConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__set_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__SetConfig *
       lora__protocol__set_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__SetConfig *)
     protobuf_c_message_unpack (&lora__protocol__set_config__descriptor,
                                allocator, len, data);
}
void   lora__protocol__set_config__free_unpacked
                     (Lora__Protocol__SetConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__set_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora__protocol__set_config_content__config_entry__init
                     (Lora__Protocol__SetConfigContent__ConfigEntry         *message)
{
  static const Lora__Protocol__SetConfigContent__ConfigEntry init_value = LORA__PROTOCOL__SET_CONFIG_CONTENT__CONFIG_ENTRY__INIT;
  *message = init_value;
}
void   lora__protocol__set_config_content__init
                     (Lora__Protocol__SetConfigContent         *message)
{
  static const Lora__Protocol__SetConfigContent init_value = LORA__PROTOCOL__SET_CONFIG_CONTENT__INIT;
  *message = init_value;
}
size_t lora__protocol__set_config_content__get_packed_size
                     (const Lora__Protocol__SetConfigContent *message)
{
  assert(message->base.descriptor == &lora__protocol__set_config_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora__protocol__set_config_content__pack
                     (const Lora__Protocol__SetConfigContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora__protocol__set_config_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora__protocol__set_config_content__pack_to_buffer
                     (const Lora__Protocol__SetConfigContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora__protocol__set_config_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lora__Protocol__SetConfigContent *
       lora__protocol__set_config_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lora__Protocol__SetConfigContent *)
     protobuf_c_message_unpack (&lora__protocol__set_config_content__descriptor,
                                allocator, len, data);
}
void   lora__protocol__set_config_content__free_unpacked
                     (Lora__Protocol__SetConfigContent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora__protocol__set_config_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lora__protocol__packet__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__Packet, type),
    &lora__protocol__packet_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advertise",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Packet, content_case),
    offsetof(Lora__Protocol__Packet, advertise),
    &lora__protocol__advertise__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle_forward",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Packet, content_case),
    offsetof(Lora__Protocol__Packet, bundle_forward),
    &lora__protocol__bundle_forward__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ping_pong",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Packet, content_case),
    offsetof(Lora__Protocol__Packet, ping_pong),
    &lora__protocol__ping_pong__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_config",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Packet, content_case),
    offsetof(Lora__Protocol__Packet, set_config),
    &lora__protocol__set_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__packet__field_indices_by_name[] = {
  1,   /* field[1] = advertise */
  2,   /* field[2] = bundle_forward */
  3,   /* field[3] = ping_pong */
  4,   /* field[4] = set_config */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange lora__protocol__packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor lora__protocol__packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.Packet",
  "Packet",
  "Lora__Protocol__Packet",
  "lora.protocol",
  sizeof(Lora__Protocol__Packet),
  5,
  lora__protocol__packet__field_descriptors,
  lora__protocol__packet__field_indices_by_name,
  1,  lora__protocol__packet__number_ranges,
  (ProtobufCMessageInit) lora__protocol__packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__lat_lng_pos__field_descriptors[2] =
{
  {
    "lat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__LatLngPos, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__LatLngPos, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__lat_lng_pos__field_indices_by_name[] = {
  0,   /* field[0] = lat */
  1,   /* field[1] = lng */
};
static const ProtobufCIntRange lora__protocol__lat_lng_pos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__lat_lng_pos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.LatLngPos",
  "LatLngPos",
  "Lora__Protocol__LatLngPos",
  "lora.protocol",
  sizeof(Lora__Protocol__LatLngPos),
  2,
  lora__protocol__lat_lng_pos__field_descriptors,
  lora__protocol__lat_lng_pos__field_indices_by_name,
  1,  lora__protocol__lat_lng_pos__number_ranges,
  (ProtobufCMessageInit) lora__protocol__lat_lng_pos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__xypos__field_descriptors[2] =
{
  {
    "X",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__XYPos, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__XYPos, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__xypos__field_indices_by_name[] = {
  0,   /* field[0] = X */
  1,   /* field[1] = Y */
};
static const ProtobufCIntRange lora__protocol__xypos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__xypos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.XYPos",
  "XYPos",
  "Lora__Protocol__XYPos",
  "lora.protocol",
  sizeof(Lora__Protocol__XYPos),
  2,
  lora__protocol__xypos__field_descriptors,
  lora__protocol__xypos__field_indices_by_name,
  1,  lora__protocol__xypos__number_ranges,
  (ProtobufCMessageInit) lora__protocol__xypos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__generic_pos__field_descriptors[1] =
{
  {
    "generic",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__GenericPos, generic),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__generic_pos__field_indices_by_name[] = {
  0,   /* field[0] = generic */
};
static const ProtobufCIntRange lora__protocol__generic_pos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lora__protocol__generic_pos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.GenericPos",
  "GenericPos",
  "Lora__Protocol__GenericPos",
  "lora.protocol",
  sizeof(Lora__Protocol__GenericPos),
  1,
  lora__protocol__generic_pos__field_descriptors,
  lora__protocol__generic_pos__field_indices_by_name,
  1,  lora__protocol__generic_pos__number_ranges,
  (ProtobufCMessageInit) lora__protocol__generic_pos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define lora__protocol__no_pos__field_descriptors NULL
#define lora__protocol__no_pos__field_indices_by_name NULL
#define lora__protocol__no_pos__number_ranges NULL
const ProtobufCMessageDescriptor lora__protocol__no_pos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.NoPos",
  "NoPos",
  "Lora__Protocol__NoPos",
  "lora.protocol",
  sizeof(Lora__Protocol__NoPos),
  0,
  lora__protocol__no_pos__field_descriptors,
  lora__protocol__no_pos__field_indices_by_name,
  0,  lora__protocol__no_pos__number_ranges,
  (ProtobufCMessageInit) lora__protocol__no_pos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__advertise__data_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__Advertise__DataEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__Advertise__DataEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__advertise__data_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange lora__protocol__advertise__data_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__advertise__data_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.Advertise.DataEntry",
  "DataEntry",
  "Lora__Protocol__Advertise__DataEntry",
  "lora.protocol",
  sizeof(Lora__Protocol__Advertise__DataEntry),
  2,
  lora__protocol__advertise__data_entry__field_descriptors,
  lora__protocol__advertise__data_entry__field_indices_by_name,
  1,  lora__protocol__advertise__data_entry__number_ranges,
  (ProtobufCMessageInit) lora__protocol__advertise__data_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__advertise__field_descriptors[6] =
{
  {
    "node_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__Advertise, node_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat_lng",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Advertise, position_case),
    offsetof(Lora__Protocol__Advertise, lat_lng),
    &lora__protocol__lat_lng_pos__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xy",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Advertise, position_case),
    offsetof(Lora__Protocol__Advertise, xy),
    &lora__protocol__xypos__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "generic",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Advertise, position_case),
    offsetof(Lora__Protocol__Advertise, generic),
    &lora__protocol__generic_pos__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_pos",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Advertise, position_case),
    offsetof(Lora__Protocol__Advertise, no_pos),
    &lora__protocol__no_pos__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__Advertise, n_data),
    offsetof(Lora__Protocol__Advertise, data),
    &lora__protocol__advertise__data_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__advertise__field_indices_by_name[] = {
  5,   /* field[5] = data */
  3,   /* field[3] = generic */
  1,   /* field[1] = lat_lng */
  4,   /* field[4] = no_pos */
  0,   /* field[0] = node_name */
  2,   /* field[2] = xy */
};
static const ProtobufCIntRange lora__protocol__advertise__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor lora__protocol__advertise__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.Advertise",
  "Advertise",
  "Lora__Protocol__Advertise",
  "lora.protocol",
  sizeof(Lora__Protocol__Advertise),
  6,
  lora__protocol__advertise__field_descriptors,
  lora__protocol__advertise__field_indices_by_name,
  1,  lora__protocol__advertise__number_ranges,
  (ProtobufCMessageInit) lora__protocol__advertise__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__bundle_forward__data_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward__DataEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward__DataEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__bundle_forward__data_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange lora__protocol__bundle_forward__data_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__bundle_forward__data_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.BundleForward.DataEntry",
  "DataEntry",
  "Lora__Protocol__BundleForward__DataEntry",
  "lora.protocol",
  sizeof(Lora__Protocol__BundleForward__DataEntry),
  2,
  lora__protocol__bundle_forward__data_entry__field_descriptors,
  lora__protocol__bundle_forward__data_entry__field_indices_by_name,
  1,  lora__protocol__bundle_forward__data_entry__number_ranges,
  (ProtobufCMessageInit) lora__protocol__bundle_forward__data_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__bundle_forward__field_descriptors[5] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward, destination),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward, bundle_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle_data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__BundleForward, bundle_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__BundleForward, n_data),
    offsetof(Lora__Protocol__BundleForward, data),
    &lora__protocol__bundle_forward__data_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__bundle_forward__field_indices_by_name[] = {
  3,   /* field[3] = bundle_data */
  2,   /* field[2] = bundle_id */
  4,   /* field[4] = data */
  1,   /* field[1] = destination */
  0,   /* field[0] = sender */
};
static const ProtobufCIntRange lora__protocol__bundle_forward__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor lora__protocol__bundle_forward__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.BundleForward",
  "BundleForward",
  "Lora__Protocol__BundleForward",
  "lora.protocol",
  sizeof(Lora__Protocol__BundleForward),
  5,
  lora__protocol__bundle_forward__field_descriptors,
  lora__protocol__bundle_forward__field_indices_by_name,
  1,  lora__protocol__bundle_forward__number_ranges,
  (ProtobufCMessageInit) lora__protocol__bundle_forward__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__ping_pong__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__PingPong, type),
    &lora__protocol__ping_pong_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__PingPong, node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__ping_pong__field_indices_by_name[] = {
  1,   /* field[1] = node_id */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange lora__protocol__ping_pong__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__ping_pong__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.PingPong",
  "PingPong",
  "Lora__Protocol__PingPong",
  "lora.protocol",
  sizeof(Lora__Protocol__PingPong),
  2,
  lora__protocol__ping_pong__field_descriptors,
  lora__protocol__ping_pong__field_indices_by_name,
  1,  lora__protocol__ping_pong__number_ranges,
  (ProtobufCMessageInit) lora__protocol__ping_pong__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__set_config__field_descriptors[2] =
{
  {
    "destination",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfig, destination),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfig, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__set_config__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = destination */
};
static const ProtobufCIntRange lora__protocol__set_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__set_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.SetConfig",
  "SetConfig",
  "Lora__Protocol__SetConfig",
  "lora.protocol",
  sizeof(Lora__Protocol__SetConfig),
  2,
  lora__protocol__set_config__field_descriptors,
  lora__protocol__set_config__field_indices_by_name,
  1,  lora__protocol__set_config__number_ranges,
  (ProtobufCMessageInit) lora__protocol__set_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__set_config_content__config_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfigContent__ConfigEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfigContent__ConfigEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__set_config_content__config_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange lora__protocol__set_config_content__config_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora__protocol__set_config_content__config_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.SetConfigContent.ConfigEntry",
  "ConfigEntry",
  "Lora__Protocol__SetConfigContent__ConfigEntry",
  "lora.protocol",
  sizeof(Lora__Protocol__SetConfigContent__ConfigEntry),
  2,
  lora__protocol__set_config_content__config_entry__field_descriptors,
  lora__protocol__set_config_content__config_entry__field_indices_by_name,
  1,  lora__protocol__set_config_content__config_entry__number_ranges,
  (ProtobufCMessageInit) lora__protocol__set_config_content__config_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora__protocol__set_config_content__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfigContent, type),
    &lora__protocol__config_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "persist",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Lora__Protocol__SetConfigContent, persist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Lora__Protocol__SetConfigContent, n_config),
    offsetof(Lora__Protocol__SetConfigContent, config),
    &lora__protocol__set_config_content__config_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora__protocol__set_config_content__field_indices_by_name[] = {
  2,   /* field[2] = config */
  1,   /* field[1] = persist */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange lora__protocol__set_config_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lora__protocol__set_config_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lora.protocol.SetConfigContent",
  "SetConfigContent",
  "Lora__Protocol__SetConfigContent",
  "lora.protocol",
  sizeof(Lora__Protocol__SetConfigContent),
  3,
  lora__protocol__set_config_content__field_descriptors,
  lora__protocol__set_config_content__field_indices_by_name,
  1,  lora__protocol__set_config_content__number_ranges,
  (ProtobufCMessageInit) lora__protocol__set_config_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue lora__protocol__packet_type__enum_values_by_number[3] =
{
  { "TYPE_ADVERTISE", "LORA__PROTOCOL__PACKET_TYPE__TYPE_ADVERTISE", 0 },
  { "TYPE_BUNDLE_FORWARD", "LORA__PROTOCOL__PACKET_TYPE__TYPE_BUNDLE_FORWARD", 1 },
  { "TYPE_PING_PONG", "LORA__PROTOCOL__PACKET_TYPE__TYPE_PING_PONG", 2 },
};
static const ProtobufCIntRange lora__protocol__packet_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex lora__protocol__packet_type__enum_values_by_name[3] =
{
  { "TYPE_ADVERTISE", 0 },
  { "TYPE_BUNDLE_FORWARD", 1 },
  { "TYPE_PING_PONG", 2 },
};
const ProtobufCEnumDescriptor lora__protocol__packet_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lora.protocol.PacketType",
  "PacketType",
  "Lora__Protocol__PacketType",
  "lora.protocol",
  3,
  lora__protocol__packet_type__enum_values_by_number,
  3,
  lora__protocol__packet_type__enum_values_by_name,
  1,
  lora__protocol__packet_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue lora__protocol__ping_pong_type__enum_values_by_number[2] =
{
  { "TYPE_PING", "LORA__PROTOCOL__PING_PONG_TYPE__TYPE_PING", 0 },
  { "TYPE_PONG", "LORA__PROTOCOL__PING_PONG_TYPE__TYPE_PONG", 1 },
};
static const ProtobufCIntRange lora__protocol__ping_pong_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex lora__protocol__ping_pong_type__enum_values_by_name[2] =
{
  { "TYPE_PING", 0 },
  { "TYPE_PONG", 1 },
};
const ProtobufCEnumDescriptor lora__protocol__ping_pong_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lora.protocol.PingPongType",
  "PingPongType",
  "Lora__Protocol__PingPongType",
  "lora.protocol",
  2,
  lora__protocol__ping_pong_type__enum_values_by_number,
  2,
  lora__protocol__ping_pong_type__enum_values_by_name,
  1,
  lora__protocol__ping_pong_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue lora__protocol__config_type__enum_values_by_number[3] =
{
  { "TYPE_ECLA", "LORA__PROTOCOL__CONFIG_TYPE__TYPE_ECLA", 0 },
  { "TYPE_DTND", "LORA__PROTOCOL__CONFIG_TYPE__TYPE_DTND", 1 },
  { "TYPE_LORA", "LORA__PROTOCOL__CONFIG_TYPE__TYPE_LORA", 2 },
};
static const ProtobufCIntRange lora__protocol__config_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex lora__protocol__config_type__enum_values_by_name[3] =
{
  { "TYPE_DTND", 1 },
  { "TYPE_ECLA", 0 },
  { "TYPE_LORA", 2 },
};
const ProtobufCEnumDescriptor lora__protocol__config_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lora.protocol.ConfigType",
  "ConfigType",
  "Lora__Protocol__ConfigType",
  "lora.protocol",
  3,
  lora__protocol__config_type__enum_values_by_number,
  3,
  lora__protocol__config_type__enum_values_by_name,
  1,
  lora__protocol__config_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
