/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <../protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Lora__Protocol__Packet Lora__Protocol__Packet;
typedef struct _Lora__Protocol__LatLngPos Lora__Protocol__LatLngPos;
typedef struct _Lora__Protocol__XYPos Lora__Protocol__XYPos;
typedef struct _Lora__Protocol__GenericPos Lora__Protocol__GenericPos;
typedef struct _Lora__Protocol__NoPos Lora__Protocol__NoPos;
typedef struct _Lora__Protocol__Advertise Lora__Protocol__Advertise;
typedef struct _Lora__Protocol__Advertise__DataEntry Lora__Protocol__Advertise__DataEntry;
typedef struct _Lora__Protocol__BundleForward Lora__Protocol__BundleForward;
typedef struct _Lora__Protocol__BundleForward__DataEntry Lora__Protocol__BundleForward__DataEntry;
typedef struct _Lora__Protocol__PingPong Lora__Protocol__PingPong;
typedef struct _Lora__Protocol__SetConfig Lora__Protocol__SetConfig;
typedef struct _Lora__Protocol__SetConfigContent Lora__Protocol__SetConfigContent;
typedef struct _Lora__Protocol__SetConfigContent__ConfigEntry Lora__Protocol__SetConfigContent__ConfigEntry;


/* --- enums --- */

typedef enum _Lora__Protocol__PacketType {
  LORA__PROTOCOL__PACKET_TYPE__TYPE_ADVERTISE = 0,
  LORA__PROTOCOL__PACKET_TYPE__TYPE_BUNDLE_FORWARD = 1,
  LORA__PROTOCOL__PACKET_TYPE__TYPE_PING_PONG = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA__PROTOCOL__PACKET_TYPE)
} Lora__Protocol__PacketType;
typedef enum _Lora__Protocol__PingPongType {
  LORA__PROTOCOL__PING_PONG_TYPE__TYPE_PING = 0,
  LORA__PROTOCOL__PING_PONG_TYPE__TYPE_PONG = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA__PROTOCOL__PING_PONG_TYPE)
} Lora__Protocol__PingPongType;
typedef enum _Lora__Protocol__ConfigType {
  LORA__PROTOCOL__CONFIG_TYPE__TYPE_ECLA = 0,
  LORA__PROTOCOL__CONFIG_TYPE__TYPE_DTND = 1,
  LORA__PROTOCOL__CONFIG_TYPE__TYPE_LORA = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA__PROTOCOL__CONFIG_TYPE)
} Lora__Protocol__ConfigType;

/* --- messages --- */

typedef enum {
  LORA__PROTOCOL__PACKET__CONTENT__NOT_SET = 0,
  LORA__PROTOCOL__PACKET__CONTENT_ADVERTISE = 2,
  LORA__PROTOCOL__PACKET__CONTENT_BUNDLE_FORWARD = 3,
  LORA__PROTOCOL__PACKET__CONTENT_PING_PONG = 4,
  LORA__PROTOCOL__PACKET__CONTENT_SET_CONFIG = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA__PROTOCOL__PACKET__CONTENT)
} Lora__Protocol__Packet__ContentCase;

struct  _Lora__Protocol__Packet
{
  ProtobufCMessage base;
  Lora__Protocol__PacketType type;
  Lora__Protocol__Packet__ContentCase content_case;
  union {
    Lora__Protocol__Advertise *advertise;
    Lora__Protocol__BundleForward *bundle_forward;
    Lora__Protocol__PingPong *ping_pong;
    Lora__Protocol__SetConfig *set_config;
  };
};
#define LORA__PROTOCOL__PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__packet__descriptor) \
    , LORA__PROTOCOL__PACKET_TYPE__TYPE_ADVERTISE, LORA__PROTOCOL__PACKET__CONTENT__NOT_SET, {0} }


struct  _Lora__Protocol__LatLngPos
{
  ProtobufCMessage base;
  float lat;
  float lng;
};
#define LORA__PROTOCOL__LAT_LNG_POS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__lat_lng_pos__descriptor) \
    , 0, 0 }


struct  _Lora__Protocol__XYPos
{
  ProtobufCMessage base;
  float x;
  float y;
};
#define LORA__PROTOCOL__XYPOS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__xypos__descriptor) \
    , 0, 0 }


struct  _Lora__Protocol__GenericPos
{
  ProtobufCMessage base;
  char *generic;
};
#define LORA__PROTOCOL__GENERIC_POS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__generic_pos__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Lora__Protocol__NoPos
{
  ProtobufCMessage base;
};
#define LORA__PROTOCOL__NO_POS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__no_pos__descriptor) \
     }


struct  _Lora__Protocol__Advertise__DataEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LORA__PROTOCOL__ADVERTISE__DATA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__advertise__data_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  LORA__PROTOCOL__ADVERTISE__POSITION__NOT_SET = 0,
  LORA__PROTOCOL__ADVERTISE__POSITION_LAT_LNG = 2,
  LORA__PROTOCOL__ADVERTISE__POSITION_XY = 3,
  LORA__PROTOCOL__ADVERTISE__POSITION_GENERIC = 4,
  LORA__PROTOCOL__ADVERTISE__POSITION_NO_POS = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA__PROTOCOL__ADVERTISE__POSITION)
} Lora__Protocol__Advertise__PositionCase;

struct  _Lora__Protocol__Advertise
{
  ProtobufCMessage base;
  char *node_name;
  size_t n_data;
  Lora__Protocol__Advertise__DataEntry **data;
  Lora__Protocol__Advertise__PositionCase position_case;
  union {
    Lora__Protocol__LatLngPos *lat_lng;
    Lora__Protocol__XYPos *xy;
    Lora__Protocol__GenericPos *generic;
    Lora__Protocol__NoPos *no_pos;
  };
};
#define LORA__PROTOCOL__ADVERTISE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__advertise__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, LORA__PROTOCOL__ADVERTISE__POSITION__NOT_SET, {0} }


struct  _Lora__Protocol__BundleForward__DataEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LORA__PROTOCOL__BUNDLE_FORWARD__DATA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__bundle_forward__data_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Lora__Protocol__BundleForward
{
  ProtobufCMessage base;
  char *sender;
  char *destination;
  char *bundle_id;
  ProtobufCBinaryData bundle_data;
  size_t n_data;
  Lora__Protocol__BundleForward__DataEntry **data;
};
#define LORA__PROTOCOL__BUNDLE_FORWARD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__bundle_forward__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0,NULL }


struct  _Lora__Protocol__PingPong
{
  ProtobufCMessage base;
  Lora__Protocol__PingPongType type;
  char *node_id;
};
#define LORA__PROTOCOL__PING_PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__ping_pong__descriptor) \
    , LORA__PROTOCOL__PING_PONG_TYPE__TYPE_PING, (char *)protobuf_c_empty_string }


struct  _Lora__Protocol__SetConfig
{
  ProtobufCMessage base;
  char *destination;
  ProtobufCBinaryData content;
};
#define LORA__PROTOCOL__SET_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__set_config__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


struct  _Lora__Protocol__SetConfigContent__ConfigEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LORA__PROTOCOL__SET_CONFIG_CONTENT__CONFIG_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__set_config_content__config_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Lora__Protocol__SetConfigContent
{
  ProtobufCMessage base;
  Lora__Protocol__ConfigType type;
  protobuf_c_boolean persist;
  size_t n_config;
  Lora__Protocol__SetConfigContent__ConfigEntry **config;
};
#define LORA__PROTOCOL__SET_CONFIG_CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora__protocol__set_config_content__descriptor) \
    , LORA__PROTOCOL__CONFIG_TYPE__TYPE_ECLA, 0, 0,NULL }


/* Lora__Protocol__Packet methods */
void   lora__protocol__packet__init
                     (Lora__Protocol__Packet         *message);
size_t lora__protocol__packet__get_packed_size
                     (const Lora__Protocol__Packet   *message);
size_t lora__protocol__packet__pack
                     (const Lora__Protocol__Packet   *message,
                      uint8_t             *out);
size_t lora__protocol__packet__pack_to_buffer
                     (const Lora__Protocol__Packet   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__Packet *
       lora__protocol__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__packet__free_unpacked
                     (Lora__Protocol__Packet *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__LatLngPos methods */
void   lora__protocol__lat_lng_pos__init
                     (Lora__Protocol__LatLngPos         *message);
size_t lora__protocol__lat_lng_pos__get_packed_size
                     (const Lora__Protocol__LatLngPos   *message);
size_t lora__protocol__lat_lng_pos__pack
                     (const Lora__Protocol__LatLngPos   *message,
                      uint8_t             *out);
size_t lora__protocol__lat_lng_pos__pack_to_buffer
                     (const Lora__Protocol__LatLngPos   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__LatLngPos *
       lora__protocol__lat_lng_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__lat_lng_pos__free_unpacked
                     (Lora__Protocol__LatLngPos *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__XYPos methods */
void   lora__protocol__xypos__init
                     (Lora__Protocol__XYPos         *message);
size_t lora__protocol__xypos__get_packed_size
                     (const Lora__Protocol__XYPos   *message);
size_t lora__protocol__xypos__pack
                     (const Lora__Protocol__XYPos   *message,
                      uint8_t             *out);
size_t lora__protocol__xypos__pack_to_buffer
                     (const Lora__Protocol__XYPos   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__XYPos *
       lora__protocol__xypos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__xypos__free_unpacked
                     (Lora__Protocol__XYPos *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__GenericPos methods */
void   lora__protocol__generic_pos__init
                     (Lora__Protocol__GenericPos         *message);
size_t lora__protocol__generic_pos__get_packed_size
                     (const Lora__Protocol__GenericPos   *message);
size_t lora__protocol__generic_pos__pack
                     (const Lora__Protocol__GenericPos   *message,
                      uint8_t             *out);
size_t lora__protocol__generic_pos__pack_to_buffer
                     (const Lora__Protocol__GenericPos   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__GenericPos *
       lora__protocol__generic_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__generic_pos__free_unpacked
                     (Lora__Protocol__GenericPos *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__NoPos methods */
void   lora__protocol__no_pos__init
                     (Lora__Protocol__NoPos         *message);
size_t lora__protocol__no_pos__get_packed_size
                     (const Lora__Protocol__NoPos   *message);
size_t lora__protocol__no_pos__pack
                     (const Lora__Protocol__NoPos   *message,
                      uint8_t             *out);
size_t lora__protocol__no_pos__pack_to_buffer
                     (const Lora__Protocol__NoPos   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__NoPos *
       lora__protocol__no_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__no_pos__free_unpacked
                     (Lora__Protocol__NoPos *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__Advertise__DataEntry methods */
void   lora__protocol__advertise__data_entry__init
                     (Lora__Protocol__Advertise__DataEntry         *message);
/* Lora__Protocol__Advertise methods */
void   lora__protocol__advertise__init
                     (Lora__Protocol__Advertise         *message);
size_t lora__protocol__advertise__get_packed_size
                     (const Lora__Protocol__Advertise   *message);
size_t lora__protocol__advertise__pack
                     (const Lora__Protocol__Advertise   *message,
                      uint8_t             *out);
size_t lora__protocol__advertise__pack_to_buffer
                     (const Lora__Protocol__Advertise   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__Advertise *
       lora__protocol__advertise__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__advertise__free_unpacked
                     (Lora__Protocol__Advertise *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__BundleForward__DataEntry methods */
void   lora__protocol__bundle_forward__data_entry__init
                     (Lora__Protocol__BundleForward__DataEntry         *message);
/* Lora__Protocol__BundleForward methods */
void   lora__protocol__bundle_forward__init
                     (Lora__Protocol__BundleForward         *message);
size_t lora__protocol__bundle_forward__get_packed_size
                     (const Lora__Protocol__BundleForward   *message);
size_t lora__protocol__bundle_forward__pack
                     (const Lora__Protocol__BundleForward   *message,
                      uint8_t             *out);
size_t lora__protocol__bundle_forward__pack_to_buffer
                     (const Lora__Protocol__BundleForward   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__BundleForward *
       lora__protocol__bundle_forward__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__bundle_forward__free_unpacked
                     (Lora__Protocol__BundleForward *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__PingPong methods */
void   lora__protocol__ping_pong__init
                     (Lora__Protocol__PingPong         *message);
size_t lora__protocol__ping_pong__get_packed_size
                     (const Lora__Protocol__PingPong   *message);
size_t lora__protocol__ping_pong__pack
                     (const Lora__Protocol__PingPong   *message,
                      uint8_t             *out);
size_t lora__protocol__ping_pong__pack_to_buffer
                     (const Lora__Protocol__PingPong   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__PingPong *
       lora__protocol__ping_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__ping_pong__free_unpacked
                     (Lora__Protocol__PingPong *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__SetConfig methods */
void   lora__protocol__set_config__init
                     (Lora__Protocol__SetConfig         *message);
size_t lora__protocol__set_config__get_packed_size
                     (const Lora__Protocol__SetConfig   *message);
size_t lora__protocol__set_config__pack
                     (const Lora__Protocol__SetConfig   *message,
                      uint8_t             *out);
size_t lora__protocol__set_config__pack_to_buffer
                     (const Lora__Protocol__SetConfig   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__SetConfig *
       lora__protocol__set_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__set_config__free_unpacked
                     (Lora__Protocol__SetConfig *message,
                      ProtobufCAllocator *allocator);
/* Lora__Protocol__SetConfigContent__ConfigEntry methods */
void   lora__protocol__set_config_content__config_entry__init
                     (Lora__Protocol__SetConfigContent__ConfigEntry         *message);
/* Lora__Protocol__SetConfigContent methods */
void   lora__protocol__set_config_content__init
                     (Lora__Protocol__SetConfigContent         *message);
size_t lora__protocol__set_config_content__get_packed_size
                     (const Lora__Protocol__SetConfigContent   *message);
size_t lora__protocol__set_config_content__pack
                     (const Lora__Protocol__SetConfigContent   *message,
                      uint8_t             *out);
size_t lora__protocol__set_config_content__pack_to_buffer
                     (const Lora__Protocol__SetConfigContent   *message,
                      ProtobufCBuffer     *buffer);
Lora__Protocol__SetConfigContent *
       lora__protocol__set_config_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora__protocol__set_config_content__free_unpacked
                     (Lora__Protocol__SetConfigContent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Lora__Protocol__Packet_Closure)
                 (const Lora__Protocol__Packet *message,
                  void *closure_data);
typedef void (*Lora__Protocol__LatLngPos_Closure)
                 (const Lora__Protocol__LatLngPos *message,
                  void *closure_data);
typedef void (*Lora__Protocol__XYPos_Closure)
                 (const Lora__Protocol__XYPos *message,
                  void *closure_data);
typedef void (*Lora__Protocol__GenericPos_Closure)
                 (const Lora__Protocol__GenericPos *message,
                  void *closure_data);
typedef void (*Lora__Protocol__NoPos_Closure)
                 (const Lora__Protocol__NoPos *message,
                  void *closure_data);
typedef void (*Lora__Protocol__Advertise__DataEntry_Closure)
                 (const Lora__Protocol__Advertise__DataEntry *message,
                  void *closure_data);
typedef void (*Lora__Protocol__Advertise_Closure)
                 (const Lora__Protocol__Advertise *message,
                  void *closure_data);
typedef void (*Lora__Protocol__BundleForward__DataEntry_Closure)
                 (const Lora__Protocol__BundleForward__DataEntry *message,
                  void *closure_data);
typedef void (*Lora__Protocol__BundleForward_Closure)
                 (const Lora__Protocol__BundleForward *message,
                  void *closure_data);
typedef void (*Lora__Protocol__PingPong_Closure)
                 (const Lora__Protocol__PingPong *message,
                  void *closure_data);
typedef void (*Lora__Protocol__SetConfig_Closure)
                 (const Lora__Protocol__SetConfig *message,
                  void *closure_data);
typedef void (*Lora__Protocol__SetConfigContent__ConfigEntry_Closure)
                 (const Lora__Protocol__SetConfigContent__ConfigEntry *message,
                  void *closure_data);
typedef void (*Lora__Protocol__SetConfigContent_Closure)
                 (const Lora__Protocol__SetConfigContent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    lora__protocol__packet_type__descriptor;
extern const ProtobufCEnumDescriptor    lora__protocol__ping_pong_type__descriptor;
extern const ProtobufCEnumDescriptor    lora__protocol__config_type__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__packet__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__lat_lng_pos__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__xypos__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__generic_pos__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__no_pos__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__advertise__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__advertise__data_entry__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__bundle_forward__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__bundle_forward__data_entry__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__ping_pong__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__set_config__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__set_config_content__descriptor;
extern const ProtobufCMessageDescriptor lora__protocol__set_config_content__config_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protocol_2eproto__INCLUDED */
